Repository YesWiki/yeswiki, pull requests merged in 2021-01, with the labels that each got.

#589 add sync between createur and owner for entries
  handlers/page/update.php
  setup/sql/default-content.sql
  tools/bazar/actions/bazarlistecategorie.php
  tools/bazar/fields/AclField.php
  tools/bazar/fields/FileField.php
  tools/bazar/fields/ImageField.php
  tools/bazar/handlers/RssHandler.php
  tools/bazar/libs/bazar.fonct.php
  tools/bazar/presentation/templates/blog.tpl.html
  tools/bazar/presentation/templates/liste_liens_date.tpl.html
  tools/bazar/services/EntryManager.php
Labels: bug, en cours

#600 More Bazar refactoring
  includes/YesWikiPerformable.php
  includes/services/Performer.php
  tools/bazar/actions/BazarAction.php
  tools/bazar/controllers/FormController.php
  tools/bazar/fields/FileField.php
  tools/bazar/fields/ImageField.php
  tools/bazar/libs/bazar.fonct.php
  tools/bazar/libs/bazar.fonct.retrocompatibility.php
  tools/bazar/services/Guard.php
  tools/bazar/templates/menu.twig
Labels: prêt

#602 Fix liste facette labels
  tools/bazar/libs/bazar.fonct.php
Labels: prêt

#601 Refactor baz_voir_fiche
  includes/YesWiki.php
  includes/services/Mailer.php
  tools/bazar/actions/BazarAction.php
  tools/bazar/controllers/EntryController.php
  tools/bazar/fields/SelectEntryField.php
  tools/bazar/handlers/RssHandler.php
  tools/bazar/handlers/page/__show.php
  tools/bazar/libs/bazar.fonct.php
  tools/bazar/libs/bazar.fonct.retrocompatibility.php
  tools/bazar/templates/entries/form.twig
  tools/bazar/templates/entries/view.twig
Labels: prêt

#620 improve link tracking for button nav include
  actions/include.php
  includes/YesWiki.php
  includes/services/LinkTracker.php
  tools/templates/actions/button.php
  tools/templates/actions/nav.php
Labels: proposition
